# 业务流程策略
policies:
  - name: default-chat-workflow
    description: 聊天任务处理流程
    steps:
      - name: validate-input
        type: validation
        timeout: 5000
      - name: llm-processing
        type: execution
        timeout: 60000
        retryPolicy:
          maxAttempts: 3
          backoff: 1000
        resources:
          - type: llm
            provider: deepseek
      - name: store-result
        type: persistence
        timeout: 10000
